include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
    - build
    - deploy

variables:
    BUNDLE: "org.gnome.Evince.flatpak"

master:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build
    when: manual

    script:
        - >
            meson 
            -Dlibhandy:examples=false -Dlibhandy:tests=false -Dlibhandy:vapi=false 
            -Dlibhandy:glade_catalog=disabled -Dlibhandy:introspection=disabled 
            _build
        - ninja -C _build all

    artifacts:
        when: on_failure
        paths:
        - _build/meson-logs/meson-log.txt
        expire_in: 2 days

meson:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build

    script:
        - >
            meson 
            -Dlibhandy:examples=false -Dlibhandy:tests=false -Dlibhandy:vapi=false 
            -Dlibhandy:glade_catalog=disabled -Dlibhandy:introspection=disabled 
            _build
        - ninja -C _build all

    artifacts:
        when: on_failure
        paths:
        - _build/meson-logs/meson-log.txt
        expire_in: 2 days

meson-internal-synctex:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build

    script:
        - meson -Dinternal_synctex=true _build
        - ninja -C _build all

    artifacts:
        when: on_failure
        paths:
        - _build/meson-logs/meson-log.txt
        expire_in: 2 days

meson-gtk-doc:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build
    when: manual

    script:
        - >
            meson -Dgtk_doc=true 
            -Dlibhandy:examples=false -Dlibhandy:tests=false -Dlibhandy:vapi=false 
            -Dlibhandy:glade_catalog=disabled -Dlibhandy:introspection=disabled 
            _build
        - ninja -C _build all 

    artifacts:
        when: on_failure
        paths:
        - _build/meson-logs/meson-log.txt
        expire_in: 2 days

flatpak:
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    stage: build

    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.Evince.json"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        FLATPAK_MODULE: "evince"
        MESON_ARGS: "-Dnautilus=false -Dgtk_doc=false"
        APP_ID: "org.gnome.Evince"
    extends: .flatpak

nightly:
    dependencies:
        - flatpak
    extends: .publish_nightly
