include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
    - build
    - deploy

variables:
    BUNDLE: "org.gnome.Evince.flatpak"

master:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build

    script:
        - ./autogen.sh --enable-debug --enable-nautilus
        - make

    artifacts:
        when: on_failure
        paths:
        - config.log
        expire_in: 2 days

meson:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build
    when: manual

    script:
        - meson _build
        - ninja -C _build all libevdocument-doc libevview-doc evince-doc

    artifacts:
        when: on_failure
        paths:
        - _build/meson-logs/meson-log.txt
        expire_in: 2 days

meson-gtk-doc:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build
    when: manual

    script:
        - meson -Dgtk_doc=true _build
        - ninja -C _build all libevdocument-doc libevview-doc evince-doc

    artifacts:
        when: on_failure
        paths:
        - _build/meson-logs/meson-log.txt
        expire_in: 2 days

gtk-doc:
    image: registry.gitlab.gnome.org/gnome/evince/master-amd64:latest
    stage: build
    when: manual

    script:
        - ./autogen.sh --enable-nautilus --enable-gtk-doc
        - make

    artifacts:
        when: on_failure
        paths:
        - config.log
        expire_in: 2 days

flatpak:
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    stage: build

    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.Evince.json"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        FLATPAK_MODULE: "evince"
        MESON_ARGS: "-Dnautilus=false -Dgtk_doc=false"
        APP_ID: "org.gnome.Evince"
    extends: .flatpak

    script:
        - flatpak-builder --stop-at=evince app ${MANIFEST_PATH}
        - flatpak build app meson --prefix=/app ${MESON_ARGS} _build
        - flatpak build app ninja -C _build install
        - flatpak-builder --finish-only --repo=_repo app ${MANIFEST_PATH}
        # Run automatic tests inside the Flatpak env
        - xvfb-run -a -s "-screen 0 1024x768x24" flatpak build app ninja -C _build test
        - flatpak build-bundle _repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} ${APP_ID}

    artifacts:
        paths:
            - ${BUNDLE}
            - _build/meson-logs/meson-log.txt
        expire_in: 2 days

    cache:
        paths:
            - .flatpak-builder/downloads
            - .flatpak-builder/git

review:
    stage: deploy
    dependencies:
        - flatpak
    extends: .review

stop_review:
    stage: deploy
    extends: .stop_review

nightly:
    dependencies:
        - flatpak
    extends: .publish_nightly
